### ISSUE TITLE
support for enter.py mode for qemu

### ISSUE THREAD

**Issue by henrik-andreasson** [pcdummy/pmxc#1]
would it be possible to support the termproxy for also the qemu as I can see the api is there.

**Comment by jochumdev** [comment]
I thought this needs a serial console attached

**Comment by jochumdev** [comment]
Asking in the forum

**Comment by jochumdev** [comment]
If that works and we have "pmxc qemu enter" we can merge "pmxc qemu" and "pmxc lxc" so there's no need to know what you connect to.

It would require to extend the list to show if its qemu or lxc.
