### ISSUE TITLE
pmxc doesn't show the containers

### ISSUE THREAD

**Issue by EvilMis** [pcdummy/pmxc#4]
`pmxc list pve1` command only shows virtual machines. In addition, the IP addresses of the machines are not shown. Pmxc is in version 6.2.1.0. Proxmox VE 6.2-6. Virtual machines have QEMU Guest Agent installed. Example in [pmxc.txt](https://github.com/pcdummy/pmxc/files/5589206/pmxc.txt)

pve1, pve2, pve3 and pve4 are cluster nodes. In addition to virtual machines, there are several containers that are not detected by pmxc.

**Comment by jochumdev** [comment]
Hi @EvilMis 

Thanks for trying pmxc and thanks for reporting the non-showing container problem. I'll check this and report back soon.

About the IP Addresses: PMXC doesn't list IP Addresses for QEMU.

Kind regards,
René

**Comment by jochumdev** [comment]
Hey @EvilMis,

i had no time to work on pmxc, still interested and experiencing that problem with non listed lxc containers?

Kind regards,

René

**Comment by EvilMis** [comment]
No. I switched to another solution that works.

**Comment by jochumdev** [comment]
Fixed now.
