### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Niemand112233** [pcdummy/pmxc#5]
Hi,
I get this error: 
`sudo pip3 install ".[performance,uvloop]"
ERROR: Directory '.[performance,uvloop]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

What's wrong?

**Comment by jochumdev** [comment]
I believe you'r not in the pmxc folder when you run pip3 install, right?

**Comment by putteg** [comment]
@pcdummy, maybe add that to install instructions?

**Comment by jochumdev** [comment]
@putteg done.
